language: generic
sudo: required
services:
  - docker

before_install:
  - docker image build -t danishm026/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danishm026/docker-react npm run test